name: painel_mentor
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #root depedencies
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  uuid: ^3.0.7
  bloc_test: ^9.1.3
  mockito: ^5.4.2
  #features
  licensed_companies:
    path: features/licensed_companies

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

