// Mocks generated by Mockito 5.4.2 from annotations
// in licensed_companies/test/doubles/use_cases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:licensed_companies/domain/usecases/put_company.dart' as _i2;
import 'package:licensed_companies/domain/usecases/get_companies.dart' as _i5;
import 'package:licensed_companies/entities.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AddCompany].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCompany extends _i1.Mock implements _i2.PutCompany {
  MockAddCompany() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(_i4.LicensedCompany? company) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [company],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetCompanies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCompanies extends _i1.Mock implements _i5.GetCompanies {
  MockGetCompanies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.LicensedCompany>?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i4.LicensedCompany>?>.value(),
      ) as _i3.Future<List<_i4.LicensedCompany>?>);
}
