// Mocks generated by Mockito 5.4.2 from annotations
// in painel_mentor/test/doubles/use_cases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:painel_mentor/features/licensed_companies/domain/entities/licenced_company.dart'
    as _i5;
import 'package:painel_mentor/features/licensed_companies/domain/usecases/add_company.dart'
    as _i3;
import 'package:painel_mentor/features/licensed_companies/domain/usecases/get_companies.dart'
    as _i6;
import 'package:painel_mentor/services/cloud_firestore_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCloudFirestoreService_0 extends _i1.SmartFake
    implements _i2.CloudFirestoreService {
  _FakeCloudFirestoreService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddCompany].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCompany extends _i1.Mock implements _i3.AddCompany {
  MockAddCompany() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CloudFirestoreService get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeCloudFirestoreService_0(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.CloudFirestoreService);
  @override
  _i4.Future<void> call(_i5.LicensedCompany? company) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [company],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GetCompanies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCompanies extends _i1.Mock implements _i6.GetCompanies {
  MockGetCompanies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CloudFirestoreService get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeCloudFirestoreService_0(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.CloudFirestoreService);
  @override
  _i4.Future<List<_i5.LicensedCompany>?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.LicensedCompany>?>.value(),
      ) as _i4.Future<List<_i5.LicensedCompany>?>);
}
